// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASuQ82PL0z5Jbqu9zABNOW6GHMRxtdGvM',
    appId: '1:111232757733:web:d2f76d5351e459e961c90c',
    messagingSenderId: '111232757733',
    projectId: 'social-app-64463',
    authDomain: 'social-app-64463.firebaseapp.com',
    storageBucket: 'social-app-64463.appspot.com',
    measurementId: 'G-T6SBDYQ9DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8kKzjvH1YLma2zKuqacGGliI_lY24ND4',
    appId: '1:111232757733:android:571dfa8a14a570b361c90c',
    messagingSenderId: '111232757733',
    projectId: 'social-app-64463',
    storageBucket: 'social-app-64463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5vMkxe8nmUN7Nsi6qmG9MN219rNbjKek',
    appId: '1:111232757733:ios:6db15b067422767661c90c',
    messagingSenderId: '111232757733',
    projectId: 'social-app-64463',
    storageBucket: 'social-app-64463.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5vMkxe8nmUN7Nsi6qmG9MN219rNbjKek',
    appId: '1:111232757733:ios:9629f9298d4201fa61c90c',
    messagingSenderId: '111232757733',
    projectId: 'social-app-64463',
    storageBucket: 'social-app-64463.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
